### ISSUE TITLE
Bug in internal function get_field_name_str_view(), cuts off last character

### ISSUE THREAD

**Issue by Ahajha** [getml/reflect-cpp#180]
Yes, I am aware this is an internal function, but I was looking to use the implementation for something and noticed that it cut off the last character. It's possible this is causing issues elsewhere.

```c++
#include <iostream>
#include <rfl/internal/get_field_names.hpp>

struct foo {
  int number;
};

int main() {
  std::cout << rfl::internal::get_field_name_str_view<foo, &foo::number>() << '\n';
}

```

I tried with GCC 11 and Clang 16 on Ubuntu 22.04, with libstdc++. Instead of printing "number", it prints "numbe".

Printing the full `std::source_location::current().function_name()` ends with `[with T = foo; auto ptr = &foo::number]`.

In that function, there are the following lines:
```c++
#if defined(__clang__)
	const auto split = func_name.substr(0, func_name.size() - 2);
	return split.substr(split.find_last_of(":.") + 1);
#elif defined(__GNUC__)
	const auto split = func_name.substr(0, func_name.size() - 2);
	return split.substr(split.find_last_of(":") + 1);
#elif defined(_MSC_VER)
```
It's possible that the `-2`s should be `-1`s, but it may be more complicated than that. I wonder if this is stdlib specific behavior rather than compiler specific. (Edit: copied my modified code. Original problem still stands).

**Comment by liuzicheng1987** [comment]
I am pretty sure the issue is the missing terminating null character. 

I am 100% sure that the function works and the `-2` and `-1` are correct. This is a very central functions, pretty much none of our tests would pass if this weren't right.

Obviously, you shouldn't be using internal functions, because there is no guarantee that the API is stable. But you seem to be aware of that and willing to take the risk.

So here is what you should do instead:

```cpp
#include <iostream>
#include <rfl/internal/get_field_names.hpp>

struct foo {
  int number;
};

int main() {
  std::cout << rfl::internal::get_field_name_str_lit<foo, &foo::number>().string_view() << '\n';
```

This will add the missing terminating character.

**Comment by liuzicheng1987** [comment]
If you are unsure that `rfl::internal::get_field_name_str_view`, just compile and run the JSON tests...they all use this function.

**Comment by Ahajha** [comment]
It appears the tests are fine, and making my change breaks the tests. Your suggestion still gives the truncated name, unfortunately. I suspect that the rest of the code is working around this behavior somehow. So good news, the library works, bad news is I can't use the function as-is.

Truthfully, I planned to just copy the one function for something externally, so I'll just make the modification there.

Thanks for the quick reply regardless, I appreciate it! Feel free to close this, I imagine you have bigger problems to work on :)

**Comment by liuzicheng1987** [comment]
@Ahajha, the problem might be that what you are doing is slightly different from what we are doing. 

We have to create this fake object in order to access the fields, but your code assumes that the fields are already known. That might be why we have an additional character that you don't have.

Feel free to copy as much of this code into your code as you see fit and make the appropriate adjustments...this is open source, after all.

**Comment by liuzicheng1987** [comment]
This is what I mean:

https://github.com/getml/reflect-cpp/blob/main/include/rfl/internal/get_fake_object.hpp

https://github.com/getml/reflect-cpp/blob/main/include/rfl/internal/get_ith_field_from_fake_object.hpp

You don't do this and that is probably the reason your `std::source_location::current().function_name()` looks slightly different from ours.
