### ISSUE TITLE
Strict json parsing, error when there are not used fields

### ISSUE THREAD

**Issue by Altren** [getml/reflect-cpp#190]
It would be nice to have some parser option, that validates json or some other values even more strictly. This is a common situation with configuration files when file is outdated and some fields were removed or renamed in the code, but `rfl::json::read` would parse this without any errors.
I want following code to fail:
```
struct Person {
  std::string first_name;
  std::string last_name;
};

std::string json_string = R"({"first_name":"Homer","last_name":"Simpson","age":36})";
auto homer = rfl::json::read<Person, rfl::ErrorIfExtra>(json_string).value();
```
In addition it would be nice to have this in the list of errors:
```
struct Person {
  std::string first_name;
  std::string last_name;
  int age;
};

std::string json_string = R"({"first_name":"Homer","last_name":"Simpson","ages":36})";
auto homer = rfl::json::read<Person, rfl::ErrorIfExtra>(json_string).value();
```
```
Failure:
due to unexpected exception with message:
  Found 2 errors:
1) Field named 'age' not found.
2) Value named 'ages' not used.
```

**Comment by Altren** [comment]
May be it make sence to use this as default behaviour and have `rfl::IgnoreExtra` that would prevent exception

**Comment by liuzicheng1987** [comment]
I have had a similar discussion before. I don't think this should be the default behaviour, because similar libraries in other languages, like Pydantic, also just ignore other fields by default.

But I think it makes sense to add a processor that would raise an error if there are extra fields.

**Comment by liuzicheng1987** [comment]
@Altren, it's still in a feature branch, but basically this is how it works:

- There is a processor called `rfl::NoExtraFields` that you can add. If you do, you will get an error message that is basically identical to what you have suggested (but adds a bit more information).
- If your struct contains `rfl::ExtraFields`, then that will override the `rfl::NoExtraFields` processor. The reasoning is that if someone adds a catch all for extra fields, then it is very clear that the intention is that he or she wants the extra fields to be added to that rather than an error being thrown.

**Comment by Altren** [comment]
Works like a charm, thank you!
