### ISSUE TITLE
Q: how to get the non-const reference of a struct field?

### ISSUE THREAD

**Issue by lixin-wei** [getml/reflect-cpp#32]
I want something like `rfl::get_field_ref<0>(x)`, so I can assign value to it.

```cpp
struct A {
  int a;
  double b;
};

A a;
rfl::get_field_ref<0>(x) = 1;
```

I dug the code a little and find `rfl::internal::to_ptr_named_tuple`, but this can only get a const pointer
```cpp
auto ptr_named_tuple = rfl::internal::to_ptr_named_tuple(homer);
ptr_named_tuple.get<0>(); // this is a const pointer.
```

So how to get an non-const reference/pointer?

Could anyone help me, thanks in advance!

**Comment by liuzicheng1987** [comment]
@lixin-wei 

Yes, I was thinking about this last week or so.

We don’t support something like rfl::get_field_ref, because it would be inefficient…you would have to extract all the fields just to get one.

However, what we can do is to offer a version of to_ptr_named_tuple that is non-const. I find this intriguing, because it would basically be like __dict__ in Python only that it would be checked at compile time.

It wouldn’t be hard either. I will build something like that over the next couple of days and let you know.

If you have any good idea for what that function should be called, let me know.

**Comment by lixin-wei** [comment]
@liuzicheng1987 Thank you so much for the quick response.

I just made it using const_cast as a walk around like this:
```
template <size_t index, typename T>
constexpr auto& GetNthField(T& t) {
  auto ptr_named_tuple = rfl::internal::to_ptr_named_tuple(t);
  auto const_ptr = ptr_named_tuple.template get<index>();

  using const_type = std::remove_pointer_t<decltype(const_ptr)>;
  using type = std::remove_const_t<const_type>;

  return *const_cast<type*>(const_ptr);
}
```

It works so I'm not in hurry now, so take your time😊 Thanks again for you quick support.

I'm also willing to contribute one if you don't have time. How do you think about my above solution? Can I simply move it to your code?

**Comment by ChemiCalChems** [comment]
`rfl::internal::bind_to_tuple` returns non-const references to fields that can be then used for whatever purpose.

**Comment by lixin-wei** [comment]
@ChemiCalChems Oh you just added this theses days right? It works perfectly, thanks a lot!

Could you please make it as public API?

**Comment by liuzicheng1987** [comment]
@ChemiCalChems , the problem with using it this way is that you wouldn't have access to the names of the fields. So, yes, you could use `rfl::internal::bind_to_tuple` to write something like @lixin-wei 's `GetNthField` (and that would be better than const casts). But implementations like this have a serious performance problem. Because you have to create references to ALL of the fields just to get one.

Just consider something like this:

```cpp
auto f1 = GetNthField<0>(my_struct); // has to get ALL the fields
auto f2 = GetNthField<1>(my_struct); // has to get ALL the fields again - very inefficient

*f1 = new_value1; 
*f2 = new_value2; 
```

Boost.PFR has the exact same problem - there is no cheap way around this.

I think the best solution would be to do something like Python's `__dict__`. In case you don't know, you can access any Python object like this:

```python
my_obj.__dict__
```

This will give you a dictionary representation of the same object. So my solution would be something like this:

```cpp
auto view = rfl::to_view(my_struct);
```

`view` would then be a named tuple, which would allow to access fields by value or by name:

```cpp
auto view = rfl::to_view(my_struct); // Gets all fields in one call -  much better

auto f1 = view.get<0>();
auto f2 = view.get<"name_of_other_field">();

// Modifies the original struct
*f1 = new_value1; 
*f2 = new_value2; 
```

The advantage here is that it would

**Comment by liuzicheng1987** [comment]
@lixin-wei , if you want to give it a go yourself, the basic idea would be to rewrite `rfl::internal::to_ptr_named_tuple` such that it supports both `const T`s and non-const `T`s. (But no const_cast, please).

Then you could just slap a convenient function called `rfl::to_view` on top of that. 

A PR is welcome. Otherwise I would do it myself over the next couple of days, when I find time.

**Comment by ChemiCalChems** [comment]
@liuzicheng1987 `rfl::internal::tuple_view` does exactly that, we just have to export it to a public interface.

**Comment by ChemiCalChems** [comment]
If this were to go ahead, I'd use `rfl::internal::bind_to_tuple` to get a tuple of references from `rfl::internal::tuple_view` and attach names to it if needed too.

**Comment by liuzicheng1987** [comment]
What we are looking for is `to_named_tuple`, but with pointers.

https://github.com/getml/reflect-cpp/blob/main/include/rfl/to_named_tuple.hpp

**Comment by lixin-wei** [comment]
@liuzicheng1987 After thinking a while I find it seems too hard for me as the first PR😂 You could go head pelase, I'll watch your incomming code and learn from it first.

**Comment by liuzicheng1987** [comment]
@lixin-wei , OK, I will do it.

**Comment by liuzicheng1987** [comment]
@lixin-wei , I have implemented the change as discussed and issued a new release (v0.4.0).
